GET http://localhost:3333/transactions HTTP/1.1

###
GET http://localhost:3333/transactions/5f58eb21-d80f-46e7-9779-2433312d1804 HTTP/1.1

###
GET http://localhost:3333/transactions/summary HTTP/1.1

###
POST http://localhost:3333/transactions HTTP/1.1
content-type: application/json

{
    "title": "Hamburguer",
    "amount": 5000,
    "type": "credit"
}